package chessGame;

public class Advice {
	static String newGameMessage = "<html>Welcome to Provenance Chess!<br>To start a new game press the 'New Game' button,<br>or if you need to learn about the chess pieces<br>press the 'Learn' button.<br><br>Come back every day to keep improving, good luck!</html>";
	static String easyEarlyGameMessage = "<html>The Earlygame sets the scene for the game to come.<br>A good chess opening will set you up for victory.<br>Get off to a good start in your game, with the following advice:<br><br><font color = 'green'>Aim to take the Centreboard with your pawns (the 4 middle squares).<br>Having control of this will help you out a lot later on!<br><br>Develop (chess terminology for 'move') Knight and Bishop pieces.</font><br><font color = 'red'> Avoid moving Castle and Queen at this moment<br>unless you really know what you're doing!</font><font color = 'green'<br>For bishops, place them on the longest diagonal lines<br>where they can get the most coverage.<br><br> Aim to castle your King.<br>This is a special type of chess move where<br> you simultaneously move your king and a castle.<br> The King moves two squares towards the castle and<br> the castle bypasses the King to land on the<br> square at the other side.<br></font><br>Against the lower AI difficulties <font color = 'green'> using<br>cheaper pieces as bait to in turn take their high<br>value pieces is a valuable strategy.</font></html>";
	static String easyMidGameMessage = "<html>The Midgame is considered by most, the most important <br> part of the chess game.<br>Many pieces are usually traded and who will emerge victorious is often<br> made clear during this phase, play carefully!<br>To maximise your chances of gaining the upper hand:<br><br><font color = 'green'>'Pin' your opponents important pieces.<br>This means an attacking piece (usually your bishop/rook)<br>is attacking an opposing piece that cannot move without exposing<br>a more valuable piece behind it.<br><br>Try to set up outposts.<br>These are knight's that are protected by a pawn.<br><br>Place bishops on major diagonals, to get good coverage.<br>As white, attack enemy pieces and take the initiative.<br>As black, play defensively</font><font color = 'red'> and punish white's mistakes.</font><font color = 'green'><br></font><font color = 'red'>Avoid losing a bishop as they are more powerful together.</font><br>Against the lower AI difficulties <font color = 'green'> using<br>cheaper pieces as bait to in turn take their high<br>value pieces is a valuable strategy.</font></html>";
	static String endGameMessage = "<html>This phase will determine the victor of the game<br>To perform at your best in this phase you should:<br><br><font color = 'green'>Make trades if you have more material </font><br><font color = 'red'> likewise avoid trades if you have less.</font><br><font color = 'green'>Move pawns to the opposing<br> end of the board to promote, if possible</font><br><font color = 'orange'>Attempt to draw if losing by making your King unable to move</font><br><font color = 'green'>Win by Checkmate by placing the opposing King<br> in check and attacking the squares he can move to.</font></html>";
	static String earlyGameMessage = "<html>Get off to a good start in your game, with the following advice:<br><br><font color = 'green'>Aim to take the Centreboard with your pawns (the 4 middle squares).<br>Having control of this will help you out a lot later on!<br><br>Develop (chess terminology for 'move') Knight and Bishop pieces.</font><br><font color = 'red'> Avoid moving Castle and Queen at this moment<br>unless you really know what you're doing!</font><font color = 'green'<br>For bishops, place them on the longest diagonal lines<br>where they can get the most coverage.<br><br> Aim to castle your King.<br>This is a special type of chess move where<br> you simultaneously move your king and a castle.<br> The King moves two squares towards the castle and<br> the castle bypasses the King to land on the<br> square at the other side.<br></font><br></html>";
	static String midGameMessage = "<html>To maximise your chances of gaining the upper hand:<br><br><font color = 'green'>'Pin' your opponents important pieces.<br>This means an attacking piece (usually your bishop/rook)<br>is attacking an opposing piece that cannot move without exposing<br>a more valuable piece behind it.<br><br>Try to set up outposts.<br>These are knight's that are protected by a pawn.<br><br>Place bishops on major diagonals, to get good coverage.<br>As white, attack enemy pieces and take the initiative.<br>As black, play defensively</font><font color = 'red'> and punish white's mistakes.</font><font color = 'green'><br></font><font color = 'red'>Avoid losing a bishop as they are more powerful together.</html>";

}
